### PR TITLE
A few changes...

### PR DESCRIPTION
**Pull request by TheHappyBee**
features:
1. You can directly enter nothing and it will tell the weather of your place. I understand that you already have one, but I feel you don't quite need geocoder to do it, you can just directly use built modules (and a little help from sites).

UI changes:
1. I felt like the "by paichiwo" was kind of squished up to the World weather logo, so I decided to simply make it a Label and place it just in the **right** place.
2. Wrong city or location is ambiguous you should probably add some other common errors, included one I added here, which is a blank API code.

### CODE REVIEW

**Comment by paichiwo** [comment]
Thank you for all your work on this project. I like the idea of new label 'paichiwo' being positioned lower. 
I also agree with adding more Error messages, you actually demonstrated a good way of doing that. Great.
There however few issues with your code:
1.  You have forked code from few days ago. (I'm constantly working on this app so this repo updated dynamically.)
      Please fetch the newest version of the code as quit a bit has changed.
2. function `get_current_location` doesn't work as it should, instead of 'Bournemouth, UK' it showed 'Belo Horizonte, BR'
3. Temperature in the current_window is cut for some reason and  looks like this: 
Zrzut ekranu 2023-05-24 120815

Would you like to correct these before the merge ?

**Review by paichiwo — CHANGES_REQUESTED** [review]
1. fork new code
2. fix get_current_location
3. fix temp label cut-off

**Comment by TheHappyBee** [comment]
thank you so much for responding I fix these errors, but I will need you to test the current_location function since I can not move to different places. Thanks :)
```
def get_current_location(link="https://ipinfo.io/city"):
    f = urllib.request.urlopen(link)
    return f.read().decode("utf-8").strip("\n")
```
Is it generating the right city for you now?

**Comment by paichiwo** [comment]
function brings an error:
image
but when in web browser:
image

we can try something like this: 
```
import requests

def get_current_location(link="https://ipinfo.io/city"):
    try:
        response = requests.get(link)
        if response.status_code == 200:
            return response.text.strip()
        else:
            return "Unable to fetch location data."
    except requests.exceptions.RequestException as e:
        return "An error occurred: " + str(e)

print(get_current_location())
```
remember that there a same city names in different countries so search current location by `city, country code` (2 letters) would be beneficial.

**Comment by TheHappyBee** [comment]
sure

**Comment by TheHappyBee** [comment]
I fixed most of the bugs and forked your most recent copy.

**Pull request merged**
