### PR TITLE
2 add unit tests

### PR DESCRIPTION
**Pull request by jhanley634**
Minor changes, which show how automated unit tests can be added to the project.

There are some mechanical structural changes that should be made soon and which I will not attempt:
- rename the main source file to "world_weather.py" so it is importable
- move all helpers to top level so they're accessible to tests

     --JH

### CODE REVIEW

**Comment by paichiwo** [comment]
Update world-weather.py
I see that you have moved the get_user_location to the top, however in the meantime I merged a pull request from another user. We decided that it would be beneficial to get rid of gecoder module and use what's already there, so module request is used instead. He also worked on better error handling.

**Comment by jhanley634** [comment]
The proposed edits do not appear to be compatible with the current project direction. Closing as WONTFIX.

**Comment by paichiwo** [comment]
i was really happy with the test you wrote and changes you made

**Comment by jhanley634** [comment]
Well, `git` never forgets. There's always an opportunity to implement a subset of those changes with the new setup.

**Comment by paichiwo** [comment]
1. moved all helpers to the top
2. renamed world-weather.py to world_weather.py
3. Implement more error handling by adding get_response_code function.
if you could please look at the changes and maybe write some test example now ?

**Pull request closed without merging**
